### PR TITLE
bump to 15.2.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Taking a shot at updating this in the wake of the new [vs2015](https://github.com/conda-forge/vs2015_runtime-feedstock)...

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like it is getting confused as it is trying to byte compile some Python 3 code with a Python 2 interpreter. Basically, this is issue ( https://github.com/conda/conda-build/issues/686 ).

**Comment by jakirkham** [comment]
Actually, I think this is why we stayed on 14.x. See this [commit]( https://github.com/pelson/staged-recipes/commit/480843089d93dac53d6bfa0330c19eb8cc492397 ).

**Comment by bollwyvl** [comment]
> Actually, I think this is why we stayed on 14.x. See this commit.

Ah, ok. So fall back to just forcing a new build number with the 14.x line? I'll give it a shot...

**Comment by bollwyvl** [comment]
Looks like #8 is the way to go!

**Pull request closed without merging**
