### PR TITLE
Pin to zeromq 4.2.1

### PR DESCRIPTION
**Pull request by SylvainCorlay**
cc @blink1073 @minrk

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender.

**Comment by SylvainCorlay** [comment]
> `@conda-forge-admin, please rerender.`

Booyah!

**Comment by blink1073** [comment]
ka-chow :boom:

**Comment by SylvainCorlay** [comment]
cf https://github.com/conda-forge/jupyterlab_launcher-feedstock/pull/28

**Comment by blink1073** [comment]
All checks passed, merge away!

**Comment by SylvainCorlay** [comment]
I don't have merge privileges!

**Comment by blink1073** [comment]
Oh noes!

**Comment by SylvainCorlay** [comment]
cc @jakirkham

**Comment by patricksnape** [comment]
@SylvainCorlay Needs to be one of

@jakirkham
@minrk
@msarahan
@pelson

**Comment by ocefpaf** [comment]
@SylvainCorlay did you send a PR to `pin_slow_way.py` to document this pin?

**Comment by SylvainCorlay** [comment]
Thanks for merging. I don't know what `pin_the_slow_way.py` is exactly.

The issue with `pyzmq` is that the `libzmq` version used at build time should be pinned to at runtime, which explicitly tries to load `libzmq.so.M.m.p` at runtime instead of the `libzmq.so` alias.

IMO it is a bug in the `setup.py` for pyzmq

**Comment by ocefpaf** [comment]
> Thanks for merging. I don't know what `pin_the_slow_way.py` is exactly.

Sorry, should've been more specific.  [`pin_the_slow_way.py`](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L128) is where we document global pinnings in conda-forge for ABI compatibility. (Something that we hope to abandon as soon as we move to conda-build 3.)

> The issue with `pyzmq` is that the `libzmq` version used at build time should be pinned to at runtime, which explicitly tries to load `libzmq.so.M.m.p` at runtime instead of the `libzmq.so` alias.
> IMO it is a bug in the `setup.py` for pyzmq.

Maybe, in that case, we don't need to modify it globally, only here.

**Comment by SylvainCorlay** [comment]
OK, so not modifying it. It looks like it is just an issue in pyzmq.

**Comment by minrk** [comment]
I believe this is a bug in libzmq, possibly caused by bugs in the continuously error-producing CMake files in zeromq. I believe the fix is for the zeromq conda package to stop using the buggy cmake files.

**Comment by minrk** [comment]
Confirmed, ZeroMQ's cmake files produce incorrect library versions which cause this problem. The fix is to stop using cmake to build libzmq (https://github.com/conda-forge/zeromq-feedstock/pull/20).

**Comment by minrk** [comment]
@ocefpaf it turns out that all packages that linked zeromq are affected, so maybe updating pin_the_slow_way is correct. There is nothing specific to pyzmq about this. While zeromq has proper ABI versioning such that `4.2.*` *should* be fine, the zeromq-4.2.1 package was built with CMake files that set the wrong ABI version, causing any patch release to be incompatible with the previous patch release due to filename changes. All libraries that linked zeromq load the wrong file such that a patch-level update will break them until they rebuild. Once conda-forge/zeromq-feedstock#20 lands, ABI versions will be future-compatible, but 4.2.1 will always be incompatible with 4.2.* unless we do a rebuild of that version.

After conda-forge/zeromq-feedstock#20, pinning zeromq to >=`4.2.3,<4.3` should be right.

**Pull request merged**
